name: secretary_example
description: A sample command-line application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  colorize: ^3.0.0
  rest_client: ^2.1.4+4
  secretary:
    path: ../

# dev_dependencies:
#   lints: ^2.0.0
