name: secretary_example
description: A sample command-line application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  colorize: ^3.0.0
  elegant: ^0.0.7
  rest_client:
    git:
      url: https://github.com/alexobviously/rest_client
      ref: main
  rxdart: ^0.27.7
  secretary:
    path: ../

# dev_dependencies:
#   lints: ^2.0.0
