name: Secretary Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get
      
      - name: Basic Tests
        run: dart test test/secretary_test.dart

      - name: Retry Policy Tests
        run: dart test test/retry_policy_test.dart